USE master;
GO
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'YUG-KUNJADIYA\Yug')
BEGIN
    CREATE LOGIN [YUG-KUNJADIYA\Yug] FROM WINDOWS;
END
GO
USE QardX;
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'YUG-KUNJADIYA\Yug')
BEGIN
    CREATE USER [YUG-KUNJADIYA\Yug] FOR LOGIN [YUG-KUNJADIYA\Yug];
END
GO
ALTER ROLE db_owner ADD MEMBER [YUG-KUNJADIYA\Yug];
GO
